
helpText = {'1,2,3: Toggles the displayed image (channel1, channel2, overlay)', ...
            'Up Arrow: Increase selected threshold (highlighted in red)', ...
            'Down Arrow: Decrease selected threshold (highlighted in red)', ...
            'Left Arrow: Go to previous slice (only works in slice mode)', ...
            'Right Arrow: Go to next slice (only works in slice mode)', ...
            'A: Toggle between streched mode and fixed aspect ratio', ...
            'B: Toggle background detections for intensity comparisons (auto-detection uses convex hull of colocalized dots and freehand tool allows arbitary masks)', ...
            'C: Toggle visibility of colocalized detections', ...
            'D: Toggle visibility of detections', ...
            'E: Export results', ...
            'H: Show this help dialog', ...
            'I: Show IDs of detections by hovering them with the mouse', ...
            'L: Show ScaLeBar at a user-defined location (lower-right corner of the scale bar)', ...
            'M: Switch between slice-mode and maximum projection mode', ...
            'O: Zoom out to the original view', ...
            'P: Preview of the percentage of colocalization before the final parameters are fixed for export', ...
            'R: Reset all thresholds', ...
            'S: Show scatter plots of the mean intensities of the current colocalizing detections', ...
            'T: Change current threshold (use 1,2,3 for changing only channel1, channel2 or both parameters, respectively)', ...
            'Mouse Wheel: Scroll through slices (only works in slice-mode)', ...
            'CTRL + Mouse Wheel: Zoom in/out in a Google-Maps like behavior', ...
            '', ...
            'Hint: In case key presses show no effect, left click once on the image and try hitting the button again. This only happens if the window looses the focus.'};

helpdlg(helpText);